In [1]:
import pandas as pd
import numpy as np

In [2]:
calender=pd.read_csv('calendar.csv')
listings=pd.read_csv('listings.csv')
neighbour=pd.read_csv('neighbourhoods.csv')
reviews=pd.read_csv('reviews.csv')
listings_brief=pd.read_csv('listings_brief.csv')
reviews_brief=pd.read_csv('reviews_brief.csv')

In [3]:
def color_negative_red(value):
    if value < 0:
        color = 'green'  
    elif value > 0:
        color = 'yellow'
    elif value=="NaN":
        color = 'red'
    elif value==str:
        color = 'green'
    else:
        color = 'red'
        
    return 'color: %s' % color

In [4]:
try:
    i = int()
except ValueError as err:
    pass

In [5]:
calender

         listing_id        date available    price
0            635756  2019-11-14         t   $67.00
1            292285  2019-11-14         f      NaN
2            292285  2019-11-13         f      NaN
3            292285  2019-11-12         f      NaN
4            292285  2019-11-11         f      NaN
5            292285  2019-11-10         f      NaN
6            292285  2019-11-09         f      NaN
7            292285  2019-11-08         f      NaN
8            292285  2019-11-07         f      NaN
9            292285  2019-11-06         f      NaN
10           292285  2019-11-05         f      NaN
11           292285  2019-11-04         f      NaN
12           292285  2019-11-03         f      NaN
13           292285  2019-11-02         f      NaN
14           292285  2019-11-01         f      NaN
15           292285  2019-10-31         f      NaN
16           292285  2019-10-30         f      NaN
17           292285  2019-10-29         f      NaN
18           292285  2019-10-28         f      NaN
19           292285  2019-10-27         f      NaN
20           292285  2019-10-26         f      NaN
21           292285  2019-10-25         f      NaN
22           292285  2019-10-24         f      NaN
23           292285  2019-10-23         f      NaN
24           292285  2019-10-22         f      NaN
25           292285  2019-10-21         f      NaN
26           292285  2019-10-20         f      NaN
27           292285  2019-10-19         f      NaN
28           292285  2019-10-18         f      NaN
29           292285  2019-10-17         f      NaN
...             ...         ...       ...      ...
4351500    29960453  2018-12-14         t  $150.00
4351501    29960453  2018-12-13         t  $150.00
4351502    29960453  2018-12-12         t  $150.00
4351503    29960453  2018-12-11         t  $150.00
4351504    29960453  2018-12-10         t  $150.00
4351505    29960453  2018-12-09         t  $150.00
4351506    29960453  2018-12-08         t  $150.00
4351507    29960453  2018-12-07         t  $150.00
4351508    29960453  2018-12-06         t  $150.00
4351509    29960453  2018-12-05         t  $150.00
4351510    29960453  2018-12-04         t  $150.00
4351511    29960453  2018-12-03         t  $150.00
4351512    29960453  2018-12-02         t  $150.00
4351513    29960453  2018-12-01         t  $150.00
4351514    29960453  2018-11-30         t  $150.00
4351515    29960453  2018-11-29         t  $150.00
4351516    29960453  2018-11-28         t  $150.00
4351517    29960453  2018-11-27         t  $150.00
4351518    29960453  2018-11-26         t  $150.00
4351519    29960453  2018-11-25         t  $150.00
4351520    29960453  2018-11-24         t  $150.00
4351521    29960453  2018-11-23         t  $150.00
4351522    29960453  2018-11-22         f      NaN
4351523    29960453  2018-11-21         f      NaN
4351524    29960453  2018-11-20         f      NaN
4351525    29960453  2018-11-19         f      NaN
4351526    29960453  2018-11-18         f      NaN
4351527    29960453  2018-11-17         f      NaN
4351528    29960453  2018-11-16         f      NaN
4351529    29960453  2018-11-15         f      NaN

[4351530 rows x 4 columns]

In [6]:
pd.set_option('display.max_columns',None)

listings.head(2)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,6,https://www.airbnb.com/rooms/6,20181115100559,2018-11-15,Large Craftsmen w/ yard ~ Perfect for families,Our Beautiful Craftsmen house has all the mode...,"We are located in the heart of North Park, the...",Our Beautiful Craftsmen house has all the mode...,none,"We have the best Neighborhood in San Diego, in...",The driveway has room for two cars to park tan...,We are right around the corner from a bus stop...,Guests will have access to everything in the h...,We will not be in town but you are welcome to ...,I know this is stated above but before you boo...,NaN,NaN,https://a0.muscache.com/im/pictures/22883194/5...,NaN,29,https://www.airbnb.com/users/show/29,Sara,2008-03-03,"San Diego, California, United States",I am a San Diego based Entrepreneur with a lov...,within an hour,100%,NaN,t,https://a0.muscache.com/im/users/29/profile_pi...,https://a0.muscache.com/im/users/29/profile_pi...,North Park,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'off...",t,f,"San Diego, CA, United States",North Park,North Hills,NaN,San Diego,CA,92104.0,San Diego,"San Diego, CA",US,United States,32.753993,-117.129705,t,House,Entire home/apt,6,2.0,3.0,4.0,Real Bed,"{TV,Internet,Wifi,""Air conditioning"",Kitchen,""...",NaN,$295.00,NaN,NaN,$0.00,$85.00,4,$5.00,2,30,4 weeks ago,t,8,8,20,20,2018-11-15,149,2008-06-22,2018-10-07,96.0,10.0,9.0,10.0,10.0,10.0,10.0,f,NaN,"{""SAN DIEGO"","" SAN DIEGO TOURISM MARKETING DIS...",t,f,strict_14_with_grace_period,f,f,1,1.18
1,5570,https://www.airbnb.com/rooms/5570,20181115100559,2018-11-15,Ocean front condo on the sand,Missionbeachretreat. Great Ocean Front Condo...,This charming two bedroom beachfront condomini...,Missionbeachretreat. Great Ocean Front Condo...,none,While some may compare San Diego’s Mission Bea...,NaN,Bus #8 goes to La Jolla and Old Town transit c...,"2 Bedrooms (1 Queen, 2 Twins) 1 Bath Balcony ...",Once reservation is made I will call guest. I...,"Min 4 nights winter. 7 nights Spring Break, l...",NaN,NaN,https://a0.muscache.com/im/pictures/d3342744-1...,NaN,8435,https://www.airbnb.com/users/show/8435,Jef Karchin'S MISSIONBEACHRETREAT,2009-02-23,"San Diego, California, United States","Real estate broker, Jef Karchin real estate ...",within a few hours,100%,NaN,f,https://a0.muscache.com/im/users/8435/profile_...,https://a0.muscache.com/im/users/8435/profile_...,Mission Beach,3.0,3.0,"['email', 'phone', 'kba']",t,t,"San Diego, CA, United States",Mission Beach,Mission Bay,NaN,San Diego,CA,92109.0,San Diego,"San Diego, CA",US,United States,32.784304,-117.252578,t,Condominium,Entire home/apt,6,1.0,2.0,4.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,Kitchen,""Free par...",850.0,"$2,050.00",NaN,NaN,$500.00,$150.00,1,$0.00,3,365,today,t,30,49,60,328,2018-11-15,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,"{""SAN DIEGO"","" SAN DIEGO TOURISM MARKETING DIS...",f,f,strict_14_with_grace_period,f,f,2,NaN

In [7]:
neighbour.head()

   neighbourhood_group                neighbourhood
0                  NaN               Allied Gardens
1                  NaN                   Alta Vista
2                  NaN  Amphitheater And Water Park
3                  NaN                  Balboa Park
4                  NaN                  Bario Logan

In [8]:
neighbour.dtypes

neighbourhood_group    float64
neighbourhood           object
dtype: object

In [9]:
listings_brief.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,6,Large Craftsmen w/ yard ~ Perfect for families,29,Sara,NaN,North Hills,32.753993,-117.129705,Entire home/apt,295,2,149,2018-10-07,1.18,1,20
1,5570,Ocean front condo on the sand,8435,Jef Karchin'S MISSIONBEACHRETREAT,NaN,Mission Bay,32.784304,-117.252578,Entire home/apt,2050,3,0,NaN,NaN,2,328
2,8095,Sunset Cliffs Studio,270,Marin,NaN,Ocean Beach,32.735170,-117.243793,Entire home/apt,84,2,178,2015-11-02,1.56,1,0
3,39516,Art Studio Retreat/Rustic Cabin,169649,Chris And Jean,NaN,North Hills,32.731884,-117.119180,Entire home/apt,69,3,338,2018-11-07,3.33,1,273
4,45429,OB cottage SD--view on waterway,197919,Melissa,NaN,Loma Portal,32.748768,-117.229371,Entire home/apt,160,2,6,2014-07-28,0.06,1,363

In [10]:
reviews_brief.head()

   listing_id        date
0           6  2008-06-22
1           6  2009-06-22
2           6  2012-07-16
3           6  2013-07-07
4           6  2013-07-08

In [11]:
#  Major factors to consider while booking the hotel
n=pd.DataFrame(listings_brief.columns)
n

                                 0
0                               id
1                             name
2                          host_id
3                        host_name
4              neighbourhood_group
5                    neighbourhood
6                         latitude
7                        longitude
8                        room_type
9                            price
10                  minimum_nights
11               number_of_reviews
12                     last_review
13               reviews_per_month
14  calculated_host_listings_count
15                availability_365

In [12]:
#  First cleaning the clander data
calender.nunique()

listing_id    11922
date            371
available         2
price          2368
dtype: int64

In [13]:
listings.isnull().sum()

id                                      0
listing_url                             0
scrape_id                               0
last_scraped                            0
name                                    2
summary                               413
space                                3160
description                           153
experiences_offered                     0
neighborhood_overview                4329
notes                                5652
transit                              4842
access                               4366
interaction                          4601
house_rules                          3462
thumbnail_url                       11922
medium_url                          11922
picture_url                             0
xl_picture_url                      11922
host_id                                 0
host_url                                0
host_name                               6
host_since                              6
host_location                          56
host_about                           3976
host_response_time                   4013
host_response_rate                   4013
host_acceptance_rate                11922
host_is_superhost                       6
host_thumbnail_url                      6
                                    ...
extra_people                            0
minimum_nights                          0
maximum_nights                          0
calendar_updated                        0
has_availability                        0
availability_30                         0
availability_60                         0
availability_90                         0
availability_365                        0
calendar_last_scraped                   0
number_of_reviews                       0
first_review                         2163
last_review                          2160
review_scores_rating                 2293
review_scores_accuracy               2299
review_scores_cleanliness            2295
review_scores_checkin                2310
review_scores_communication          2301
review_scores_location               2313
review_scores_value                  2315
requires_license                        0
license                             11874
jurisdiction_names                    507
instant_bookable                        0
is_business_travel_ready                0
cancellation_policy                     0
require_guest_profile_picture           0
require_guest_phone_verification        0
calculated_host_listings_count          0
reviews_per_month                    2163
Length: 96, dtype: int64

In [14]:
listings.shape

(11922, 96)

As we have the neighbourhood we should first focus on the city

Drop columns with 90% or more missing data

In [15]:
drop_cols=[]
for i in listings.columns:
    if listings[i].isnull().sum()>10000:
        drop_cols.append(i)
print('no of clos : ',len(drop_cols))
print(drop_cols)
listings.drop(drop_cols,axis=1,inplace=True)

no of clos :  9
['thumbnail_url', 'medium_url', 'xl_picture_url', 'host_acceptance_rate', 'neighbourhood_group_cleansed', 'square_feet', 'weekly_price', 'monthly_price', 'license']

In [16]:
listings.shape

(11922, 87)

For listings_brief

In [17]:
listings_brief.isnull().sum()

id                                    0
name                                  2
host_id                               0
host_name                             6
neighbourhood_group               11922
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                        2160
reviews_per_month                  2163
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [18]:
listings_brief.shape

(11922, 16)

Dropping neighbourhood_group as it has all null values

In [19]:
listings_brief.drop('neighbourhood_group',axis=1,inplace=True)

In [20]:
listings_brief.shape

(11922, 15)

As city is our priority

In [21]:
listings.city.unique()

array(['San Diego', 'La Jolla', 'La Jolla ', 'Del Mar', 'Solana Beach',
       'San Diego ', 'Chula Vista', 'Oceanside', 'University heights',
       'Ocean Beach', 'la jolla', 'Mission Beach', 'San diego',
       'La jolla', 'Lemon Grove', 'Ocean Beach, San Diego', 'LA JOLLA',
       'Coronado', 'Escondido', 'Chula Vista ', 'La Jolla, San Diego',
       'Alpine', 'La Mesa', 'SAN DIEGO', 'Del Mar Highlands ',
       'San Diego, CA, United States', 'San Diego, California, US',
       'سان دييغو', 'Pacific Beach', 'Chula Vista,', ' La Jolla',
       'La Jolla Shores', 'Mission Bay', 'Bonita', 'Newport Beach',
       'Santee', 'National City', 'Gas lamp San Diego', 'Pacific Beach ',
       'San DIego', 'CA', 'Chula Vista (Eastlake)', 'SanDiego',
       'Spring Valley', 'Tijuana', 'Sandiego', 'Imperial Beach'],
      dtype=object)

In [22]:
listings['price'] = listings['price'].replace('[\$,]','',regex=True).astype(float)

In [23]:
listing=pd.merge(listings,listings_brief)

In [ ]:
listing.city.replace( 'La Jolla ', 'La Jolla',inplace = True)
listing.city.replace( 'la jolla', 'La Jolla',inplace = True)
listing.city.replace( 'La jolla', 'La Jolla',inplace = True)
listing.city.replace( 'LA JOLLA', 'La Jolla',inplace = True)
listing.city.replace( 'La Jolla, San Diego', 'La Jolla',inplace = True)
listing.city.replace( 'La Jolla Shores', 'La Jolla',inplace = True)
listing.city.replace( ' La Jolla', 'La Jolla',inplace = True)
listing.city.replace( 'SAN DIEGO', 'San Diego',inplace = True)
listing.city.replace( 'San Diego, California, US', 'San Diego',inplace = True)
listing.city.replace( 'San Diego ', 'San Diego',inplace = True)
listing.city.replace( 'San diego ', 'San Diego',inplace = True)
listing.city.replace( 'Ocean Beach, San Diego', 'Ocean Beach',inplace = True)
listing.city.replace( 'San diego', 'San Diego',inplace = True)
listing.city.replace( 'Pacific Beach ', 'Pacific Beach',inplace = True)
listing.city.replace( 'Del Mar Highlands ', 'Del Mar',inplace = True)
listing.city.unique()

array(['La Jolla', 'San Diego', 'Del Mar', 'Ocean Beach', 'La Mesa',
       'Alpine', 'سان دييغو', 'Pacific Beach', 'Newport Beach',
       'Gas lamp San Diego', 'National City', 'CA', 'Solana Beach'],
      dtype=object)

In [ ]:
listing.shape

(5327, 87)

In [ ]:
listing.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,54001,https://www.airbnb.com/rooms/54001,20181115100559,2018-11-15,"La Jolla Peaceful: Sitting Room, Breakfast",NaN,The Peaceful is one of two bedrooms in the de...,The Peaceful is one of two bedrooms in the de...,none,"Tranquility, stately trees, meditative, zen-fu...",Also on Airbnb and available at the same prope...,If you are debating between renting a car or '...,All common areas.,As much or little as guests prefer.,"Available for responsible, independent, educat...",https://a0.muscache.com/im/pictures/5e771b01-3...,252692,https://www.airbnb.com/users/show/252692,Marsha,2010-10-04,"San Diego, California, United States","As a La Jolla native, I have seen many change...",within an hour,100%,t,https://a0.muscache.com/im/users/252692/profil...,https://a0.muscache.com/im/users/252692/profil...,La Jolla,4.0,4.0,"['email', 'phone', 'reviews', 'kba']",t,t,"La Jolla, CA, United States",La Jolla,La Jolla,La Jolla,CA,92037.0,San Diego,"La Jolla, CA",US,United States,32.811896,-117.269516,t,House,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Wifi,Kitchen,Breakfast,""Free st...",105.0,NaN,NaN,1,$0.00,2,365,a week ago,t,0,13,43,304,2018-11-15,174,2011-01-04,2018-10-28,98.0,10.0,10.0,10.0,10.0,10.0,10.0,f,"{""SAN DIEGO"","" SAN DIEGO TOURISM MARKETING DIS...",f,f,flexible,f,t,4,1.82
1,62274,https://www.airbnb.com/rooms/62274,20181115100559,2018-11-15,"charming, colorful, close to beach","Modern, cozy, artsy, European in lush garden s...",I am offering a big room with private entrance...,"Modern, cozy, artsy, European in lush garden s...",none,"We are in walking distance to Starbucks, Trade...",NaN,"We have bikes for you to get to the beach, but...",You have your own studio with private entrance...,I will leave enough space for the guests priva...,"dear guests, Please open the bathroom window a...",https://a0.muscache.com/im/pictures/84577734/9...,302986,https://www.airbnb.com/users/show/302986,Isabel,2010-11-28,"San Diego, California, United States","i am originally from germany, but live since 1...",within an hour,100%,f,https://a0.muscache.com/im/users/302986/profil...,https://a0.muscache.com/im/users/302986/profil...,Pacific Beach,2.0,2.0,"['email', 'phone', 'reviews', 'kba']",t,t,"San Diego, CA, United States",Pacific Beach,Pacific Beach,San Diego,CA,92109.0,San Diego,"San Diego, CA",US,United States,32.807337,-117.242432,t,Guesthouse,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{Wifi,""Air conditioning"",""Free parking on prem...",68.0,$100.00,$25.00,1,$10.00,2,30,a week ago,t,9,13,33,249,2018-11-15,460,2010-12-05,2018-10-30,95.0,10.0,10.0,10.0,10.0,10.0,10.0,f,"{""SAN DIEGO"","" SAN DIEGO TOURISM MARKETING DIS...",f,f,strict_14_with_grace_period,t,t,2,4.75
2,62949,https://www.airbnb.com/rooms/62949,20181115100559,2018-11-15,Pacific Beach Cozy Bright Private Unit w Bikes,Wonderful Cozy Private Retreat. Included are u...,This unit is a wonderful cozy private little o...,Wonderful Cozy Private Retreat. Included are u...,none,"This is the best part of Pacific Beach, we are...",STRICT NO SMOKING OF ANY KIND IN UNIT IF YOU D...,We provide 2 Beach Cruisers also main Bus line...,"2 Beach Cruisers, Cooler, Beach Towels and Be...",As much as is necessary. I am available 24/7 b...,No Smoking in Room but there is a little deck ...,https://a0.muscache.com/im/pictures/27127221/c...,21532,https://www.airbnb.com/users/show/21532,Lisa,2009-06-14,"San Diego, California, United States","I have a wonderful home in Pacific Beach, Cali...",within an hour,100%,t,https://a0.muscache.com/im/users/21532/profile...,https://a0.muscache.com/im/users/21532/profile...,Pacific Beach,2.0,2.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,f,"San Diego, CA, United States",Pacific Beach,Pacific Beach,San Diego,CA,92109.0,San Diego,"San Diego, CA",US,United States,32.809612,-117.230563,t,Guest suite,Entire home/apt,2,1.0,0.0,1.0,Real Bed,"{TV,""Cable TV"",Wifi,""Air conditioning"",""Pets a...",75.0,$100.00,$20.00,1,$0.00,1,10,today,t,10,25,43,119,2018-11-15,498,2012-08-23,2018-11-10,97.0,10.0,10.0,10.0,10.0,10.0,10.0,f,"{""SAN DIEGO"","" SAN DIEGO TOURISM MARKETING DIS...",t,f,moderate,f,f,2,6.56
3,103417,https://www.airbnb.com/rooms/103417,20181115100559,2018-11-15,La Jolla Retreat-Garden View-Breakfast,NaN,The Retreat enjoys a queen size bed with down ...,The Retreat enjoys a queen size bed with down ...,none,"Tranquility, stately trees, meditative, zen-fu...",Also on Airbnb and available at the same prope...,If you are debating between renting a car or '...,All common areas.,As much or little as desired,"Available for responsible, independent, educat...",https://a0.muscache.com/im/pictures/56552093/0...,252692,https://www.airbnb.com/users/show/252692,Marsha,2010-10-04,"San Diego, California, United States","As a La Jolla native, I have seen many change...",within an hour,100%,t,https://a0.muscache.com/im/users/252692/profil...,https://a0.muscache.com/im/users/252692/profil...,La Jolla,4.0,4.0,"['email', 'phone', 'reviews', 'kba']",t,t,"La Jolla , CA, United States",La Jolla,La Jolla,La Jolla,CA,92037.0,San Diego,"La Jolla , CA",US,United States,32.812803,-117.267470,t,House,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,Kitchen,Breakfast...",125.0,NaN,NaN,1,$0.00,2,365,today,t,5,35,63,79,2018-11-15,145,2011-08-16,2018-09-30,98.0,10.0,10.0,10.0,10.0,10.0,10.0,f,"{""SAN DIEGO"","" SAN DIEGO TOURISM MARKETING DIS...",f,f,flexible,f,t,4,1.64
4,103420,https://www.airbnb.com/rooms/103420,20181115100559,2018-11-15,"La Jolla Serene: Private Patio, Breakfast",NaN,The Serene is one of two bedrooms in the deta...,The Serene is one of two bedrooms in the deta...,none,"Mother Nature, walkability-bikeability, Calume...","When staying in the La Jolla Serene, one has t...",If you are debating between renting a car or '...,All common areas.,As much or as little as guest prefers.,"Available for responsible, independent, educat...",https://a0.muscache.com/im/pictures/2695226/07...,252692,https://www.airbnb.com/users/show/252692,Marsha,2010-10-04,"San Diego, California, United States","As a La Jolla native, I have seen many change...",within an hour,100%,t,https://a0.muscache.com/im/users/252692/profil...,https://a0.muscache.com/im/users/252692/profil...,La Jolla,4.0,4.0,"['email', 'phone', 'reviews', 'kba']",t,t,"La Jolla, CA, United States",La Jolla,La Jolla,La Jolla,CA,92037.0,San Diego,"La Jolla, CA",US,United States,32.812529,-117.267722,t,House,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Wifi,Kitchen,Breakfast,""Free st...",115.0,$0.00,$0.00,1,$0.00,2,365,a week ago,t,4,22,52,160,2018-11-15,113,2011-11-10,2018-11-12,98.0,10.0,10.0,10.0,10.0,10.0,10.0,f,"{""SAN DIEGO"","" SAN DIEGO TOURISM MARKETING DIS...",f,f,flexible,f,t,4,1.32

In [ ]:
#listing.isnull().sum()

In [ ]:
listing.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       'notes', 'transit', 'access', 'interaction', 'house_rules',
       'picture_url', 'host_id', 'host_url', 'host_name', 'host_since',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_is_superhost', 'host_thumbnail_url',
       'host_picture_url', 'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'street',
       'neighbourhood', 'neighbourhood_cleansed', 'city', 'state', 'zipcode',
       'market', 'smart_location', 'country_code', 'country', 'latitude',
       'longitude', 'is_location_exact', 'property_type', 'room_type',
       'accommodates', 'bathrooms', 'bedrooms', 'beds', 'bed_type',
       'amenities', 'price', 'security_deposit', 'cleaning_fee',
       'guests_included', 'extra_people', 'minimum_nights', 'maximum_nights',
       'calendar_updated', 'has_availability', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'calendar_last_scraped', 'number_of_reviews', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'requires_license', 'jurisdiction_names',
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count', 'reviews_per_month'],
      dtype='object')

For calender

In [ ]:
calender.head()

   listing_id        date available   price
0      635756  2019-11-14         t  $67.00
1      292285  2019-11-14         f     NaN
2      292285  2019-11-13         f     NaN
3      292285  2019-11-12         f     NaN
4      292285  2019-11-11         f     NaN

In [ ]:
calender['price'] = calender['price'].replace('[\$,]','',regex=True).astype(float)

In [ ]:
calender.style.applymap(color_negative_red, subset="price")

In [ ]:
# ratings vs pricing
listing.plot.scatter(y='price', x='review_scores_rating')

In [ ]:
# Distribution of price for listing
sns.distplot(listing["price"],axlabel="Distribution of price")

price mean

In [ ]:
listing.price.mean()

In [ ]:
# pricing vs bathroom
sns.barplot(x = listing.bathrooms, y = listing.price)

In [ ]:
# pricing vs bedroom
sns.barplot(x = listing.bedrooms, y = listing.price)

In [ ]:
#  pricing vs no of persons can be accomodated
sns.barplot(x = listing.accommodates, y = listing.price)

In [ ]:
# top 10 neighbourhood places preferred
listing.groupby("neighbourhood")["review_scores_rating"].sum().sort_values(ascending=False).head(10).plot(kind="bar")

In [ ]:
# City has more price
listing.groupby('city')[['price']].sum().sort_values(by='price',ascending=False).head(10).style.applymap(color_negative_red, subset="price")

In [ ]:
import seaborn as sns
sns.heatmap(listing.corr())

In [ ]:
# super host vs rating
super_rating=listing.groupby("host_is_superhost")["review_scores_rating"].sum()
super_rating

In [ ]:
import matplotlib.pyplot as plt
labels=np.array(super_rating.index)
sizes=super_rating.values
colors=['red','blue']
plt.figure(figsize=(5,3))
plt.pie(sizes,labels=labels,colors=colors,autopct='%1.1f%%')
plt.title('rating vs super host')
plt.axis('equal')

In [ ]:
# property type vs price
listing.groupby("property_type")["price"].sum().reset_index().sort_values('price', ascending=False).head(5)